"""Sources tracked by Apprentix that are NOT fetched automatically.

They appear in data/sources.json (and on the Data & sources page) so the site
documents the whole landscape, including what it cannot automate and why.
"""

MANUAL = [
    {
        "id": "cedefop-apprenticeship-schemes",
        "name": "Cedefop — European database on apprenticeship schemes",
        "publisher": "Cedefop",
        "homepage": "https://www.cedefop.europa.eu/en/tools/apprenticeship-schemes",
        "description": "Scheme and country fiches (45 variables; 2016, 2019, 2023 and 2026 updates). The basis of the apprenticeship-schemes dataset on this site.",
        "access": "manual",
        "browser_cors": False,
        "licence": "Cedefop legal notice: reproduction authorised with acknowledgement",
        "cadence": "about every three years",
        "why_manual": "Web pages only, behind bot protection that refuses automated requests. Curated by hand; a bulk export has been requested.",
        "used_by": ["apprenticeship-schemes"],
    },
    {
        "id": "cedefop-financing-apprenticeships",
        "name": "Cedefop — Financing apprenticeships database",
        "publisher": "Cedefop",
        "homepage": "https://www.cedefop.europa.eu/en/tools/financing-apprenticeships",
        "description": "Financing arrangements for 29 schemes and 54 instruments. Reference period 2016–17 (not updated since).",
        "access": "manual",
        "browser_cors": False,
        "licence": "Cedefop legal notice: reproduction authorised with acknowledgement",
        "cadence": "not updated",
        "why_manual": "Web pages only, behind bot protection.",
    },
    {
        "id": "cedefop-nqf-online-tool",
        "name": "Cedefop — NQF online tool",
        "publisher": "Cedefop",
        "homepage": "https://www.cedefop.europa.eu/en/tools/nqfs-online-tool",
        "description": "National qualifications frameworks in 41 countries, state of play 2018, 2020, 2022, 2024.",
        "access": "manual",
        "browser_cors": False,
        "licence": "Cedefop legal notice: reproduction authorised with acknowledgement",
        "cadence": "every two years",
        "why_manual": "Web pages and PDF reports only, behind bot protection.",
    },
    {
        "id": "cedefop-vet-in-europe",
        "name": "Cedefop — VET in Europe database",
        "publisher": "Cedefop and ReferNet",
        "homepage": "https://www.cedefop.europa.eu/en/tools/vet-in-europe",
        "description": "Descriptions of national VET systems, system charts and 'Spotlight on VET' summaries.",
        "access": "manual",
        "browser_cors": False,
        "licence": "Cedefop legal notice: reproduction authorised with acknowledgement",
        "cadence": "about every two years per country",
        "why_manual": "Long-form web pages and PDFs; best linked and summarised rather than copied.",
    },
    {
        "id": "cedefop-financing-adult-learning",
        "name": "Cedefop — Financing adult learning database",
        "publisher": "Cedefop",
        "homepage": "https://www.cedefop.europa.eu/en/tools/financing-adult-learning-db",
        "description": "Training funds, tax incentives, individual learning accounts, vouchers and payback clauses (reference years 2014–15 and 2020).",
        "access": "manual",
        "browser_cors": False,
        "licence": "Cedefop legal notice: reproduction authorised with acknowledgement",
        "cadence": "irregular",
        "why_manual": "Web pages only, behind bot protection.",
    },
    {
        "id": "eafa-pledges",
        "name": "European Alliance for Apprenticeships — members and pledges",
        "publisher": "European Commission, DG EMPL",
        "homepage": "https://employment-social-affairs.ec.europa.eu/policies-and-activities/skills-and-qualifications/working-together/european-alliance-apprenticeships/eafa-membership-and-pledges_en",
        "description": "About 540 pledges by companies, chambers, social partners and others (2025).",
        "access": "manual",
        "browser_cors": False,
        "licence": "EC-reuse",
        "cadence": "continuous",
        "why_manual": "Published only as an interactive map and list; no download found. An export can be requested from DG EMPL.",
    },
    {
        "id": "etf-data-portal",
        "name": "European Training Foundation — Data portal",
        "publisher": "ETF",
        "homepage": "https://www.etf.europa.eu/en/publications-and-resources/data-portal",
        "description": "Torino Process monitoring and education, skills and employment indicators for EU candidate and neighbouring countries.",
        "access": "manual",
        "browser_cors": False,
        "licence": "unverified",
        "cadence": "annual",
        "why_manual": "Dashboards only; no API or bulk download found.",
    },
    {
        "id": "eures",
        "name": "EURES — European job mobility portal",
        "publisher": "European Labour Authority",
        "homepage": "https://eures.europa.eu/",
        "description": "Job vacancies across Europe, including apprenticeships.",
        "access": "manual",
        "browser_cors": False,
        "licence": "unverified",
        "cadence": "continuous",
        "why_manual": "No official open API; the portal's internal search is undocumented and its reuse terms are unclear. Not integrated.",
    },
    {
        "id": "education-training-monitor",
        "name": "Education and Training Monitor",
        "publisher": "European Commission, DG EAC",
        "homepage": "https://op.europa.eu/webpub/eac/education-and-training-monitor/en/index.html",
        "description": "Annual EU and country analysis, including the VET learner-mobility target (12% by 2030).",
        "access": "manual",
        "browser_cors": False,
        "licence": "EC-reuse",
        "cadence": "annual (November)",
        "why_manual": "Per-chart spreadsheet downloads; most series already come from Eurostat directly.",
    },
    {
        "id": "gisco-boundaries",
        "name": "Eurostat GISCO — administrative boundaries",
        "publisher": "Eurostat / EuroGeographics",
        "homepage": "https://gisco-services.ec.europa.eu/distribution/v2/nuts/",
        "description": "NUTS boundary files for maps.",
        "access": "manual",
        "browser_cors": None,
        "licence": "Non-commercial use only; © EuroGeographics for the administrative boundaries",
        "cadence": "per NUTS edition",
        "why_manual": "Not used: the site draws a tile-grid map instead, which needs no boundary data and has no licence restriction.",
    },
]
