"""Retrieval index for "Ask Apprentix" (the AI assistant, see worker/).

  data/ai/search-index.json                      compact text chunks the Worker searches (BM25)
  data/ai/records/vet-qualifications/<cc>.json   slim per-country shards of the Europass
                                                 qualifications (the full records.json is too
                                                 large to load inside a Cloudflare Worker)

Each chunk is {id, url, title, kind, country_code?, text}: plain text written from the
published data, with absolute https://apprentix.eu/… URLs the assistant cites. Nothing
here is generated by a model; it is a re-statement of data/published/.

Deterministic: no clock, sorted inputs, files rewritten only when their content changes.
Called at the end of pipeline/build.py all(); run on its own with
    python -m pipeline.build_ai_index
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from urllib.parse import quote, urlencode

from .common import DATA, INDICATORS, PUBLISHED, ROOT, read_json

SITE = "https://apprentix.eu/"
OUT = DATA / "ai"
INDEX = OUT / "search-index.json"
SHARDS = OUT / "records"
INSIGHTS = PUBLISHED / "insights" / "insights.json"

LONG = 700          # characters kept of a long text field
MAX_INDEX_BYTES = 6_000_000


# ---------------------------------------------------------------- helpers --

def clip(s, n: int = LONG) -> str:
    s = " ".join(str(s or "").split())
    return s if len(s) <= n else s[: n - 1].rstrip() + "…"


def fmt(v) -> str:
    if v is None or v == "" or v == []:
        return ""
    if isinstance(v, list):
        return "; ".join(str(x) for x in v if x not in (None, ""))
    return str(v)


def explore(dataset: str, open_id: str | None = None, **filters) -> str:
    params = [("dataset", dataset)] + [(f"f.{k}", v) for k, v in filters.items()]
    if open_id:
        params.append(("open", open_id))
    return SITE + "pages/explore.html?" + urlencode(params, quote_via=quote)


def country_url(code: str) -> str:
    return f"{SITE}pages/countries/{code.lower()}.html"


def indicator_url(iid: str) -> str:
    return f"{SITE}pages/indicators/{quote(iid)}.html"


def dataset_url(did: str) -> str:
    return f"{SITE}pages/datasets/{quote(did)}.html"


def chunk(id_: str, url: str, title: str, kind: str, text: str, cc: str | None = None) -> dict:
    c = {"id": id_, "url": url, "title": title, "kind": kind}
    if cc:
        c["country_code"] = cc
    c["text"] = text.strip()
    return c


def record_text(meta: dict, rec: dict, skip: set[str] = frozenset(), long: int = LONG) -> str:
    """'Label: value' lines for every described field of a record, in meta order."""
    lines = []
    for f in meta["fields"]:
        k, t = f["key"], f.get("type")
        if k in skip or t == "hidden" or k == "id":
            continue
        v = fmt(rec.get(k))
        if not v:
            continue
        if t == "longtext":
            v = clip(v, long)
        lines.append(f"{f.get('label', k)}: {v}")
    return "\n".join(lines)


def write_if_changed(path: Path, text: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


# ---------------------------------------------------------------- sections --

def default_obs(ind: dict) -> dict[tuple[str, str], dict]:
    """(geo, time) -> observation at the default breakdown (same rule as the country pages)."""
    dims = ind.get("dims") or []
    best = {}
    for o in ind.get("series", []):
        if all((o.get("dims") or {}).get(d["key"], d.get("default")) == d.get("default") for d in dims):
            best[(o["geo"], o["time"])] = o
    return best


def indicator_chunks(index: list[dict], names: dict[str, str], fmt_value) -> list[dict]:
    out = []
    for meta in sorted(index, key=lambda m: m["id"]):
        ind = read_json(INDICATORS / f"{meta['id']}.json")
        p = ind.get("provenance") or {}
        unit = ind.get("unit")
        obs = default_obs(ind)
        latest: dict[str, dict] = {}
        for (g, t), o in obs.items():
            if g not in latest or t > latest[g]["time"]:
                latest[g] = o
        dims_txt = "; ".join(
            f"{d.get('label', d['key'])} (key '{d['key']}', default '{d.get('default')}' = {d['values'].get(d.get('default'), '')}; "
            f"{len(d['values'])} values)" for d in ind.get("dims") or [])
        lines = [
            f"Indicator: {ind['title']} (id {ind['id']})",
            f"Topic: {ind.get('topic', '')}. Unit: {unit or 'n/a'}.",
            f"Definition: {clip(ind.get('description'), 900)}",
        ]
        if ind.get("comparability"):
            lines.append(f"Comparability: {clip(ind['comparability'], 900)}")
        if ind.get("national"):
            lines.append("National statistic: definitions are the country's own and NOT comparable with other countries.")
        if ind.get("target"):
            lines.append(f"Target: {ind['target'].get('label', '')}")
        if dims_txt:
            lines.append(f"Breakdowns: {dims_txt}. Values below are for the default breakdown.")
        lines.append(f"Publisher: {p.get('publisher', '')} ({p.get('dataset_code', '')}); licence {p.get('licence', 'see source')}; source {p.get('source_url', '')}")
        cov = ind.get("coverage") or {}
        if cov.get("time"):
            lines.append(f"Years covered: {cov['time'][0]}–{cov['time'][-1]}.")
        geos = sorted(latest, key=lambda g: (g != "EU27", g))
        single = len([g for g in geos if g != "EU27"]) <= 1
        if single:
            # One country: give the whole default series (e.g. a national count over time).
            series = sorted(obs.values(), key=lambda o: (o["geo"], o["time"]))
            if series and len(series[0]["time"]) > 4:
                # Monthly/quarterly: the last period of each year, then the last 6 periods.
                last_of_year = {}
                for o in series:
                    last_of_year[o["time"][:4]] = o
                tail = series[-6:]
                series = [o for o in last_of_year.values() if o not in tail] + tail
            vals = ", ".join(f"{o['time']}: {fmt_value(o['value'], unit)}{' (' + o['flag'] + ')' if o.get('flag') else ''}" for o in series[-40:])
            if geos:
                lines.append(f"Series for {names.get(geos[0], geos[0])}: {vals}")
        else:
            vals = "; ".join(
                f"{g} {latest[g]['time']}: {fmt_value(latest[g]['value'], unit)}{' (' + latest[g]['flag'] + ')' if latest[g].get('flag') else ''}"
                for g in geos)
            lines.append(f"Latest value per country: {vals}")
            eu = sorted((t, o) for (g, t), o in obs.items() if g == "EU27")
            if len(eu) > 1:
                lines.append("EU-27 trend: " + ", ".join(f"{t}: {fmt_value(o['value'], unit)}" for t, o in eu[-8:]))
        if ind.get("flags"):
            lines.append("Flags: " + "; ".join(f"{k} = {v}" for k, v in sorted(ind["flags"].items())))
        cc = geos[0] if single and geos and geos[0] != "EU27" else None
        out.append(chunk(f"indicator:{ind['id']}", indicator_url(ind["id"]), ind["title"], "indicator", "\n".join(lines), cc))
    return out


def dataset_chunks(manifest: dict) -> list[dict]:
    out = []
    for d in manifest["datasets"]:
        meta = read_json(ROOT / d["path"] / "meta.json")
        records = read_json(ROOT / d["path"] / "records.json")
        src = meta.get("source", {})
        fields = []
        for f in meta["fields"]:
            if f.get("type") == "hidden" and f["key"] not in ("country_code",):
                continue
            desc = f"{f['key']} ({f.get('label', '')}, {f.get('type', '')})"
            if f.get("type") == "category":
                cnt = Counter(x for r in records for x in (r.get(f["key"]) if isinstance(r.get(f["key"]), list) else [r.get(f["key"])]) if x not in (None, ""))
                if f["key"] not in ("country",) and len(cnt) <= 40:
                    top = [v for v, _ in sorted(cnt.items(), key=lambda kv: (-kv[1], str(kv[0])))[:12]]
                    desc += " values: " + " | ".join(str(v) for v in top)
                else:
                    desc += f" ({len(cnt)} distinct values)"
            fields.append(desc)
        text = "\n".join([
            f"Dataset: {d['title']} (id {d['id']}), {len(records):,} records. {d.get('tagline', '')}",
            f"Coverage: {d.get('coverage', '')}",
            f"Description: {clip(meta.get('description'), 1200)}",
            f"Source: {src.get('name', '')} {src.get('url', '')}. Licence: {clip(src.get('licence'), 300)}",
            f"Caveat: {clip(src.get('caveat'), 900)}",
            f"Explore: {explore(d['id'])}",
            "Fields (use with query_records): " + "; ".join(fields),
        ])
        out.append(chunk(f"dataset:{d['id']}", dataset_url(d["id"]), d["title"], "dataset", text))
    return out


def scheme_chunks(meta: dict, records: list[dict]) -> list[dict]:
    out = []
    for r in sorted(records, key=lambda r: r["id"]):
        cc = r.get("country_code")
        text = f"Apprenticeship scheme in {r.get('country')}: {r.get('name_en')} ({r.get('name_original', '')}).\n" + record_text(meta, r, long=1200)
        out.append(chunk(f"scheme:{r['id']}", f"{country_url(cc)}#scheme-{r['id']}" if cc else explore("apprenticeship-schemes", r["id"]),
                         f"{r.get('name_en')} — {r.get('country')}", "scheme", text, cc))
    return out


def simple_record_chunks(did: str, kind: str, meta: dict, records: list[dict], title_key: str, long: int = LONG) -> list[dict]:
    out = []
    for r in sorted(records, key=lambda r: r["id"]):
        title = f"{r.get(title_key)} — {r.get('country')}" if r.get("country") and r.get("country") != r.get(title_key) else str(r.get(title_key))
        text = f"{meta.get('title', did)} record.\n" + record_text(meta, r, long=long)
        out.append(chunk(f"{kind}:{r['id']}", explore(did, r["id"]), title, kind, text, r.get("country_code")))
    return out


def policy_chunks(meta: dict, records: list[dict]) -> list[dict]:
    out = []
    for r in sorted(records, key=lambda r: r["id"]):
        cc = r.get("country_code")
        if r.get("concerns_apprenticeship") == "Yes":
            lines = [
                f"VET policy (concerns apprenticeship) in {r.get('country')}: {r.get('title')}",
                f"Type: {fmt(r.get('type'))}. Latest stage: {fmt(r.get('latest_stage'))} ({fmt(r.get('latest_year'))}). First reported: {fmt(r.get('first_year'))}.",
                f"Themes: {fmt(r.get('themes'))}",
                f"Target groups: {fmt(r.get('target_groups'))}",
                f"Subsystem: {fmt(r.get('subsystem'))}. Progress: {fmt(r.get('progress'))}",
                f"Objectives: {clip(r.get('objectives'), 400)}",
                f"Description: {clip(r.get('description'), 500)}",
            ]
            kind = "policy"
        else:
            lines = [f"VET policy in {r.get('country')}: {r.get('title')} ({fmt(r.get('type'))}; latest {fmt(r.get('latest_stage'))} {fmt(r.get('latest_year'))}). Not flagged as concerning apprenticeship."]
            kind = "policy-other"
        out.append(chunk(f"policy:{r['id']}", explore("vet-policy-timeline", r["id"]), f"{r.get('title')} — {r.get('country')}",
                         kind, "\n".join(lines), cc))
    return out


def cove_chunks(meta: dict, records: list[dict]) -> list[dict]:
    out = []
    for r in sorted(records, key=lambda r: r["id"]):
        text = "\n".join([
            f"Centre of Vocational Excellence (CoVE) project {r.get('acronym')}: {r.get('project_title')} (call {r.get('call_year')}).",
            f"Coordinator: {r.get('coordinator')} ({r.get('coordinator_country')}). {r.get('roles', '')}.",
            f"Countries involved: {fmt(r.get('countries'))}",
        ])
        out.append(chunk(f"cove:{r['id']}", explore("cove-projects", r["id"]), f"{r.get('acronym')} (CoVE)", "cove",
                         text, r.get("coordinator_country_code")))
    return out


def per_country_counts(records: list[dict], key: str) -> str:
    c = Counter(x for r in records for x in (r.get(key) if isinstance(r.get(key), list) else [r.get(key)]) if x not in (None, ""))
    return ", ".join(f"{v} {n:,}" for v, n in sorted(c.items(), key=lambda kv: (-kv[1], str(kv[0]))))


def qualification_summaries(records: list[dict], names: dict[str, str]) -> list[dict]:
    """The Europass qualifications are summarised per country, not indexed one by one."""
    by: dict[str, list] = {}
    for r in records:
        by.setdefault(r.get("country_code") or "", []).append(r)
    out = []
    for cc in sorted(k for k in by if k):
        rs = by[cc]
        app = [r for r in rs if r.get("apprenticeship") == "Apprenticeship / dual"]
        fields = Counter(x for r in rs for x in (r.get("field") or []))
        text = "\n".join([
            f"National VET qualifications in {names.get(cc, cc)} published to Europass (QDR): {len(rs):,} qualifications at EQF levels 2–5.",
            f"By EQF level: {per_country_counts(rs, 'eqf_level')}.",
            f"Apprenticeship / work-based route flag: {per_country_counts(rs, 'apprenticeship')}.",
            f"Largest fields of education: {', '.join(f'{k} {n:,}' for k, n in sorted(fields.items(), key=lambda kv: (-kv[1], kv[0]))[:8])}.",
            "Examples of apprenticeship qualifications: " + "; ".join(sorted({r['title'] for r in app})[:12]) if app else "No qualification is flagged as an apprenticeship route in the register.",
            "Coverage depends on what the national authority has published to Europass; counts are not comparable between countries.",
            f"Search them with query_records(dataset_id='vet-qualifications', filters={{'country_code': '{cc}'}}, text=...).",
        ])
        out.append(chunk(f"vet-qualifications:{cc}", explore("vet-qualifications", country=names.get(cc, cc)) if cc in names else explore("vet-qualifications"),
                         f"VET qualifications in {names.get(cc, cc)} (Europass)", "qualifications-summary", text, cc))
    return out


def catalogue_summaries(records: list[dict], names: dict[str, str]) -> list[dict]:
    by: dict[str, list] = {}
    for r in records:
        by.setdefault(r.get("country_code") or "EU", []).append(r)
    out = []
    for cc in sorted(by):
        rs = by[cc]
        app = sorted((r for r in rs if r.get("concerns_apprenticeship") == "Yes"), key=lambda r: r["id"])
        pubs = Counter(r.get("publisher") for r in rs if r.get("publisher") and r.get("publisher") != "Not stated")
        label = names.get(cc, "EU-level and unassigned publishers")
        text = "\n".join([
            f"Open datasets on apprenticeship and VET from {label} listed on data.europa.eu: {len(rs):,} ({len(app):,} specifically about apprenticeship).",
            f"Main publishers: {', '.join(f'{k} ({n})' for k, n in sorted(pubs.items(), key=lambda kv: (-kv[1], kv[0]))[:6])}.",
            "Apprenticeship datasets include: " + "; ".join(clip(r.get("title"), 120) for r in app[:10]) if app else "",
        ])
        out.append(chunk(f"data-catalogue:{cc}", explore("data-catalogue", country=rs[0].get("country")) if rs[0].get("country") else explore("data-catalogue"),
                         f"Open datasets — {label}", "catalogue-summary", text, cc if cc in names else None))
    return out


def erasmus_summaries(records: list[dict], names: dict[str, str]) -> list[dict]:
    by: dict[str, list] = {}
    for r in records:
        if r.get("country_code"):
            by.setdefault(r["country_code"], []).append(r)
    out = []
    for cc in sorted(by):
        rs = by[cc]
        text = "\n".join([
            f"Erasmus+ accredited VET organisations (KA120-VET, calls 2021–2025) in {names.get(cc, cc)}: {len(rs):,}.",
            f"By type: {per_country_counts(rs, 'org_type')}.",
            f"By accreditation year: {per_country_counts(rs, 'accreditation_years')}.",
            f"Status: {per_country_counts(rs, 'status')}.",
        ])
        out.append(chunk(f"erasmus-vet-organisations:{cc}", explore("erasmus-vet-organisations", country=rs[0].get("country")),
                         f"Erasmus+ accredited VET organisations — {names.get(cc, cc)}", "erasmus-summary", text, cc))
    return out


def nqf_chunks(records: list[dict], names: dict[str, str]) -> list[dict]:
    by: dict[str, list] = {}
    for r in records:
        by.setdefault(r.get("country") or "", []).append(r)
    out = []
    for country in sorted(by):
        rs = by[country]
        cc = rs[0].get("country_code")
        lines = [f"Qualification levels in the national qualifications framework of {country} (Cedefop NQF online tool, state of play {rs[0].get('reference_year', '2024')}). Each line: qualification type — national level — EQF level{' — apprenticeship/craft' }."]
        for r in sorted(rs, key=lambda r: r["id"]):
            lines.append(f"- {r.get('qualification_type')} — NQF {r.get('nqf_level', '')} — {fmt(r.get('eqf_level')) or 'EQF not stated'}{' — APPRENTICESHIP/CRAFT' if r.get('apprenticeship_or_craft') == 'Yes' else ''}")
        lines.append(f"Source: {rs[0].get('source_url', '')}")
        slug = "-".join("".join(ch if ch.isalnum() else " " for ch in country.lower()).split())
        out.append(chunk(f"nqf:{slug}", explore("nqf-qualification-levels", country=country),
                         f"NQF qualification levels — {country}", "nqf", "\n".join(lines), cc))
    return out


def country_chunks(D, facts: dict, fmt_value, key_figures, names) -> list[dict]:
    out = []
    for c in D["countries"]:
        code = c["code"]
        f = facts.get(code)
        if not f:
            continue
        name = c["name"]
        url = country_url(code)
        lines = [f"Country profile: {name} ({code}). Apprentix page: {url}"]
        if f["schemes"]:
            lines.append(f"Apprenticeship schemes ({len(f['schemes'])}, Cedefop database on apprenticeship schemes):")
            for s in f["schemes"]:
                lines.append(
                    f"- {s.get('name_en')} ({s.get('name_original', '')}): level {fmt(s.get('education_level_detail') or s.get('education_level'))}; "
                    f"duration {fmt(s.get('duration'))}; workplace {fmt(s.get('workplace_time'))} ({fmt(s.get('workplace_time_detail'))}); "
                    f"pay {fmt(s.get('compensation'))}; Cedefop coded pay {fmt(s.get('q_compensation'))}; minimum workplace share {fmt(s.get('q_min_workplace_share'))}; "
                    f"learner status {fmt(s.get('q_learner_status'))}; contract {fmt(s.get('q_contract_type'))}; apprentices {fmt(s.get('learners'))}; "
                    f"qualification {fmt(s.get('qualification'))}; access to higher education {fmt(s.get('q_access_to_he'))}; share of VET learners {fmt(s.get('q_share_of_vet'))}.")
        rows, national = key_figures(D, code)
        if rows:
            lines.append("Key figures (latest; EU-27 same year where published):")
            for r in rows:
                ind, o, eu = r["ind"], r["obs"], r["eu"]
                lines.append(f"- {ind['title']} [{ind['id']}]: {fmt_value(o['value'], ind.get('unit'))} ({o['time']}{', flag ' + o['flag'] if o.get('flag') else ''})"
                             + (f"; EU-27 {fmt_value(eu['value'], ind.get('unit'))}" if eu else "")
                             + f" — {(ind.get('provenance') or {}).get('publisher', '')}")
        if national:
            lines.append("National statistics (own definitions; not comparable across countries):")
            for r in national:
                ind, o = r["ind"], r["obs"]
                lines.append(f"- {ind['title']} [{ind['id']}]: {fmt_value(o['value'], ind.get('unit'))} ({o['time']}) — {(ind.get('provenance') or {}).get('publisher', '')}")
        if f["policies"]:
            recent = sorted(f["app_policies"], key=lambda p: (p.get("latest_year") or "", p.get("first_year") or "", p["id"]), reverse=True)[:8]
            lines.append(f"VET policies since 2015 (Cedefop/ReferNet timeline): {len(f['policies'])}, of which {len(f['app_policies'])} concern apprenticeship. Most recent apprenticeship policies: "
                         + "; ".join(f"{p.get('title')} ({fmt(p.get('type'))}, {fmt(p.get('latest_stage'))} {fmt(p.get('latest_year'))})" for p in recent))
        fi = f["financing_instruments"]
        if fi:
            lines.append(f"Financing instruments for apprenticeships (Cedefop, 2016–17 reference period): " + "; ".join(f"{r['title']} ({fmt(r.get('type'))})" for r in fi))
        nq = f["nqf_qualification_levels"]
        app_q = [q for q in nq if q.get("apprenticeship_or_craft") == "Yes"]
        if nq:
            lines.append(f"National qualifications framework: {len(nq)} qualification types; apprenticeship/craft ones: "
                         + ("; ".join(f"{q['qualification_type']} (NQF {q.get('nqf_level', '')}, {fmt(q.get('eqf_level')) or 'EQF not stated'})" for q in app_q) or "none named"))
        if f["vet_systems"]:
            v = f["vet_systems"][0]
            lines.append(f"VET system description: Cedefop VET in Europe ({v.get('version', '')}), by {v.get('refernet_partner', '')}: {v.get('source_url', '')}")
        if f["recognition_vet_qualifications"]:
            lines.append("Recognition of foreign VET qualifications: mapped by Cedefop (2026) for " + ", ".join(r.get("system") or r["country"] for r in f["recognition_vet_qualifications"]) + ".")
        if f["erasmus_vet_organisations"]:
            lines.append(f"Erasmus+ accredited VET organisations: {len(f['erasmus_vet_organisations']):,}.")
        if f["cove_projects"]:
            coord = [r for r in f["cove_projects"] if r.get("coordinator_country_code") == code]
            lines.append(f"Centres of Vocational Excellence: takes part in {len(f['cove_projects'])} projects, coordinating {len(coord)}.")
        if f["catalogue"]:
            capp = sum(1 for r in f["catalogue"] if r.get("concerns_apprenticeship") == "Yes")
            lines.append(f"Open datasets on data.europa.eu: {len(f['catalogue'])} ({capp} on apprenticeship).")
        lines.append(f"Indicators with data for {name}: {len(f['indicators'])}.")
        out.append(chunk(f"country:{code}", url, f"{name} — apprenticeships and VET", "country", "\n".join(lines), code))
    return out


def insight_chunks() -> list[dict]:
    if not INSIGHTS.exists():
        return []
    try:
        data = read_json(INSIGHTS)
    except Exception:
        return []
    items = data if isinstance(data, list) else (data.get("insights") or data.get("items") or [])
    out = []
    for it in items:
        if not isinstance(it, dict) or not it.get("id"):
            continue
        cav = it.get("caveats") or it.get("caveat") or ""
        lines = [f"Insight: {it.get('title', '')}", f"Finding: {fmt(it.get('finding'))}"]
        if it.get("detail"):
            lines.append(f"Detail: {clip(fmt(it.get('detail')), 600)}")
        if cav:
            lines.append(f"Caveats: {clip(fmt(cav), 600)}")
        cc = it.get("country_code") if isinstance(it.get("country_code"), str) else None
        out.append(chunk(f"insight:{it['id']}", f"{SITE}pages/insights.html#{quote(str(it['id']))}", str(it.get("title", it["id"])),
                         "insight", "\n".join(lines), cc))
    return sorted(out, key=lambda c: c["id"])


GUIDE = [
    ("guide:about", SITE + "pages/about.html", "About Apprentix",
     "Apprentix (apprentix.eu) is an independent, non-commercial project that republishes public European data on "
     "apprenticeship and vocational education and training (VET): Cedefop, Eurostat, OECD, UNESCO UIS, the European "
     "Commission (Erasmus+, Europass, data.europa.eu) and national statistics offices. It is not affiliated with any EU "
     "institution. The original publishers remain authoritative. It does not run apprenticeships, place learners or "
     "give legal, financial or careers advice; learners and employers should use official national services to apply."),
    ("guide:comparability", SITE + "pages/data.html", "Comparability caveats",
     "How to read the figures: national statistics (e.g. France DARES, UK DfE, Norway SSB, Finland StatFin, Switzerland BFS, "
     "Ireland CSO, Netherlands DUO) use each country's own definitions of apprenticeship and must not be compared across "
     "countries. Eurostat's ED3SW / 'combined school- and work-based' enrolment is a proxy for work-based VET, not a count "
     "of apprentices. The Cedefop financing-instruments database refers to 2016–17 and has not been updated. Europass "
     "qualification counts depend on what each country has published. Values with flags (b break, u low reliability, "
     "e estimated, p provisional) need care. EU targets: 82% employment rate of recent VET graduates by 2025 and at least "
     "60% of recent VET graduates exposed to work-based learning (Council Recommendation on VET, 2020)."),
    ("guide:compare", SITE + "pages/compare.html", "Scheme comparison matrix",
     "The comparison matrix sets every apprenticeship scheme against Cedefop's 34 coded questions (pay, workplace share, "
     "contract, learner status, governance, incentives, qualification). Use it to compare schemes across countries."),
]


def guide_chunks() -> list[dict]:
    return [chunk(i, u, t, "guide", x) for i, u, t, x in GUIDE]


# ---------------------------------------------------------------- shards --

# Slim rows: the Worker rebuilds europass_url from the id ("qdr-<uuid>"), and treats a missing
# "apprenticeship" as "Not stated". Learning-outcome summaries are left out (size).
SHARD_FIELDS = ["id", "title", "title_original", "eqf_level", "nqf_level", "apprenticeship", "field",
                "awarding_body", "duration", "credits", "volume"]


def qualification_shards(records: list[dict]) -> list[Path]:
    by: dict[str, list] = {}
    for r in records:
        if r.get("country_code"):
            by.setdefault(r["country_code"], []).append(r)
    folder = SHARDS / "vet-qualifications"
    written, expected = [], set()
    for cc in sorted(by):
        rows = []
        for r in sorted(by[cc], key=lambda r: r["id"]):
            row = {k: r[k] for k in SHARD_FIELDS if r.get(k) not in (None, "", [], "Not stated")}
            if row.get("title_original") == row.get("title"):
                row.pop("title_original")
            rows.append(row)
        path = folder / f"{cc}.json"
        expected.add(path.name)
        text = "[\n" + ",\n".join(json.dumps(x, ensure_ascii=False, separators=(",", ":")) for x in rows) + "\n]\n"
        if write_if_changed(path, text):
            written.append(path)
    if folder.exists():
        for p in folder.glob("*.json"):
            if p.name not in expected:
                p.unlink()
                written.append(p)
    return written


# ---------------------------------------------------------------- entry --

def build() -> dict:
    from .render_pages import country_facts, fmt_value, has_content, key_figures, load

    D = load()
    names = {c["code"]: c["name"] for c in D["ref"]["countries"]}
    names["EU27"] = "EU-27"
    facts = {}
    for c in D["countries"]:
        f = country_facts(D, c["code"])
        if has_content(f):
            facts[c["code"]] = f

    def ds(did):
        p = PUBLISHED / did
        if not (p / "records.json").exists():
            return None, []
        return read_json(p / "meta.json"), read_json(p / "records.json")

    chunks: list[dict] = []
    chunks += guide_chunks()
    chunks += country_chunks(D, facts, fmt_value, key_figures, names)
    chunks += indicator_chunks(D["index"], names, fmt_value)
    chunks += dataset_chunks(D["manifest"])
    m, r = ds("apprenticeship-schemes")
    if m:
        chunks += scheme_chunks(m, r)
    m, r = ds("financing-instruments")
    if m:
        chunks += simple_record_chunks("financing-instruments", "financing", m, r, "title", long=500)
    m, r = ds("recognition-vet-qualifications")
    if m:
        chunks += simple_record_chunks("recognition-vet-qualifications", "recognition", m, r, "system", long=600)
    m, r = ds("vet-systems")
    if m:
        chunks += simple_record_chunks("vet-systems", "vet-system", m, r, "title", long=400)
    m, r = ds("vet-policy-timeline")
    if m:
        chunks += policy_chunks(m, r)
    m, r = ds("cove-projects")
    if m:
        chunks += cove_chunks(m, r)
    m, r = ds("nqf-qualification-levels")
    if m:
        chunks += nqf_chunks(r, names)
    m, r = ds("erasmus-vet-organisations")
    if m:
        chunks += erasmus_summaries(r, names)
    m, r = ds("data-catalogue")
    if m:
        chunks += catalogue_summaries(r, names)
    m, r = ds("vet-qualifications")
    shards = []
    if m:
        chunks += qualification_summaries(r, names)
        shards = qualification_shards(r)
    chunks += insight_chunks()

    ids = [c["id"] for c in chunks]
    dupes = {i for i in ids if ids.count(i) > 1}
    if dupes:
        raise ValueError(f"duplicate AI index chunk ids: {sorted(dupes)[:5]}")

    body = {
        "description": "Search index for Ask Apprentix (worker/). Text chunks restating data/published/; generated by pipeline/build_ai_index.py — do not edit.",
        "updated": D["updated"],
        "count": len(chunks),
        "shards": {"vet-qualifications": sorted(p.stem for p in (SHARDS / "vet-qualifications").glob("*.json"))},
    }
    head = json.dumps(body, ensure_ascii=False, separators=(",", ":"))[:-1]
    text = head + ',"chunks":[\n' + ",\n".join(json.dumps(c, ensure_ascii=False, separators=(",", ":")) for c in chunks) + "\n]}\n"
    size = len(text.encode("utf-8"))
    if size > MAX_INDEX_BYTES:
        print(f"warning: AI search index is {size / 1e6:.1f} MB (limit {MAX_INDEX_BYTES / 1e6:.0f} MB)")
    changed = write_if_changed(INDEX, text)
    kinds = Counter(c["kind"] for c in chunks)
    print(f"AI index: {len(chunks)} chunks, {size / 1e6:.2f} MB ({', '.join(f'{k} {n}' for k, n in sorted(kinds.items()))})"
          f"{'' if changed else ' (unchanged)'}; {len(shards)} shard file(s) changed")
    return {"chunks": len(chunks), "bytes": size, "kinds": dict(kinds)}


if __name__ == "__main__":
    build()
